DROP DATABASE IF EXISTS CT519_Movie;

CREATE DATABASE CT519_Movie;

USE CT519_Movie;

DROP TABLE IF EXISTS Movie;

CREATE TABLE Movie(
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	Code TinyInt NOT NULL,
	Director VARCHAR(50) NOT NULL,
	Show_date datetime NOT NULL,
	Trailler VARCHAR(500) NULL
);

DROP TABLE IF EXISTS Movie_Type;

CREATE TABLE Movie_Type(
	Code TinyInt NOT NULL,
	Type_name VARCHAR(100) NOT NULL
);
